name: lime
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  google_sign_in: ^6.1.5
  firebase_storage: ^11.5.0
  cloud_firestore: ^4.13.0
  google_fonts: ^6.1.0
  grouped_list: ^5.1.2
  intl: ^0.18.1
  http: ^1.1.0
  dio: ^5.3.3
  flutter_chat_bubble: ^2.0.2
  flutter_native_splash: ^2.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
    android: 'launcher_icon'
    ios: true
    image_path: 'assets/images/teamlime.jpg'


flutter_native_splash:
    image: assets/images/teamlime.jpg
    color: "#1c171d"
flutter:
  uses-material-design: true

  assets:
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

