// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt_tPjE_P3MQMxSUgbdpYlOX_cxQEmVdo',
    appId: '1:593641195579:web:4c6c38e8aa013af4d1f41e',
    messagingSenderId: '593641195579',
    projectId: 'amiu-f4ae1',
    authDomain: 'amiu-f4ae1.firebaseapp.com',
    storageBucket: 'amiu-f4ae1.appspot.com',
    measurementId: 'G-EXZ7YSCE57',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb1joQfO686K-iUdLMX4CzhOAE_Pg60zE',
    appId: '1:593641195579:android:0ef18f22d6331de9d1f41e',
    messagingSenderId: '593641195579',
    projectId: 'amiu-f4ae1',
    storageBucket: 'amiu-f4ae1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBugpPltUg3mn-ZET5IHtf6SdyhWj2yq5w',
    appId: '1:593641195579:ios:b64bfa5da4002d03d1f41e',
    messagingSenderId: '593641195579',
    projectId: 'amiu-f4ae1',
    storageBucket: 'amiu-f4ae1.appspot.com',
    iosClientId: '593641195579-e9m44a6ubrvqbrlip1l5lrktuhlap50f.apps.googleusercontent.com',
    iosBundleId: 'com.example.lime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBugpPltUg3mn-ZET5IHtf6SdyhWj2yq5w',
    appId: '1:593641195579:ios:3706021d7717d115d1f41e',
    messagingSenderId: '593641195579',
    projectId: 'amiu-f4ae1',
    storageBucket: 'amiu-f4ae1.appspot.com',
    iosClientId: '593641195579-voh8vad3hr5948tp2lqqkrclrf0olg1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.lime.RunnerTests',
  );
}
